require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FindingAidsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # FindingAid. As you add validations to FindingAid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FindingAidsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all finding_aids as @finding_aids" do
      finding_aid = FindingAid.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:finding_aids)).to eq([finding_aid])
    end
  end

  describe "GET show" do
    it "assigns the requested finding_aid as @finding_aid" do
      finding_aid = FindingAid.create! valid_attributes
      get :show, {:id => finding_aid.to_param}, valid_session
      expect(assigns(:finding_aid)).to eq(finding_aid)
    end
  end

  describe "GET new" do
    it "assigns a new finding_aid as @finding_aid" do
      get :new, {}, valid_session
      expect(assigns(:finding_aid)).to be_a_new(FindingAid)
    end
  end

  describe "GET edit" do
    it "assigns the requested finding_aid as @finding_aid" do
      finding_aid = FindingAid.create! valid_attributes
      get :edit, {:id => finding_aid.to_param}, valid_session
      expect(assigns(:finding_aid)).to eq(finding_aid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FindingAid" do
        expect {
          post :create, {:finding_aid => valid_attributes}, valid_session
        }.to change(FindingAid, :count).by(1)
      end

      it "assigns a newly created finding_aid as @finding_aid" do
        post :create, {:finding_aid => valid_attributes}, valid_session
        expect(assigns(:finding_aid)).to be_a(FindingAid)
        expect(assigns(:finding_aid)).to be_persisted
      end

      it "redirects to the created finding_aid" do
        post :create, {:finding_aid => valid_attributes}, valid_session
        expect(response).to redirect_to(FindingAid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved finding_aid as @finding_aid" do
        post :create, {:finding_aid => invalid_attributes}, valid_session
        expect(assigns(:finding_aid)).to be_a_new(FindingAid)
      end

      it "re-renders the 'new' template" do
        post :create, {:finding_aid => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested finding_aid" do
        finding_aid = FindingAid.create! valid_attributes
        put :update, {:id => finding_aid.to_param, :finding_aid => new_attributes}, valid_session
        finding_aid.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested finding_aid as @finding_aid" do
        finding_aid = FindingAid.create! valid_attributes
        put :update, {:id => finding_aid.to_param, :finding_aid => valid_attributes}, valid_session
        expect(assigns(:finding_aid)).to eq(finding_aid)
      end

      it "redirects to the finding_aid" do
        finding_aid = FindingAid.create! valid_attributes
        put :update, {:id => finding_aid.to_param, :finding_aid => valid_attributes}, valid_session
        expect(response).to redirect_to(finding_aid)
      end
    end

    describe "with invalid params" do
      it "assigns the finding_aid as @finding_aid" do
        finding_aid = FindingAid.create! valid_attributes
        put :update, {:id => finding_aid.to_param, :finding_aid => invalid_attributes}, valid_session
        expect(assigns(:finding_aid)).to eq(finding_aid)
      end

      it "re-renders the 'edit' template" do
        finding_aid = FindingAid.create! valid_attributes
        put :update, {:id => finding_aid.to_param, :finding_aid => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested finding_aid" do
      finding_aid = FindingAid.create! valid_attributes
      expect {
        delete :destroy, {:id => finding_aid.to_param}, valid_session
      }.to change(FindingAid, :count).by(-1)
    end

    it "redirects to the finding_aids list" do
      finding_aid = FindingAid.create! valid_attributes
      delete :destroy, {:id => finding_aid.to_param}, valid_session
      expect(response).to redirect_to(finding_aids_url)
    end
  end

end
